import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { createPortal } from "react-dom";
import {
  NO_ENVIRONMENT,
  type AdminToken,
  type TokenListQuery,
} from "../lib/tokenPermissionsApi";
import { DataTable } from "./ui/DataTable";
import { useTable, type ColumnDef } from "./ui/useTable";
import { RowMenu } from "./ui/RowMenu";
import { CopyButton } from "./ui/CopyButton";
import { Toggle } from "./ui/Toggle";
import { Badge } from "./ui/Badge";
import AdminSelect from "./AdminSelect";
import { EMPTY, dateSortValue } from "../lib/format";
import {
  ACCESS_BADGE,
  EXPIRY_WARNING_DAYS,
  accessDetail,
  accessLabel,
  accessStateOf,
  validityOf,
} from "../lib/tokenDisplay";
import "./TokensTable.css";

/* The Tokens table: one row per token record the token service has
 * issued, with the module permissions that govern it reachable from the row
 * itself (the modal is owned by AdminDashboard, exactly as the portal-user
 * permissions modal is).
 *
 * The row deliberately shows the token's *identity* (which environment and
 * account it acts for, which Wrike user generated it, and what it is allowed
 * to do) and never the credential it carries. An admin who needs the token
 * value uses the console's token tooling; this screen can't leak it because
 * the API never sends it. */

/* ── Advanced filters ─────────────────────────────────────────────────
   The table's own search box is one substring over the whole row; this is
   the per-column version of it, one control per column that can meaningfully
   be narrowed (every column except Actions, which is a menu).

   The definitions below are the single authority for the *controls*: they
   render the inputs and they name the query parameter each one sends. What
   each control matches is decided by the server
   (src/utils/tokenFilters.js), because it is the server that now applies the
   filter — a filter applied in the browser only ever narrows the rows the
   browser happens to hold.

   The panel edits a DRAFT. Nothing is fetched until Done, so a half-typed
   account id does not become a query, and the count in the footer always
   describes what is on screen rather than what is in the boxes. */

type FilterKey =
  | "env"
  | "tokenId"
  | "client"
  | "account"
  | "creator"
  | "access"
  | "validity"
  | "updated"
  | "status";

/** The nine controls, keyed the way the table and the pages talk about them. */
export type TokenFilters = Record<FilterKey, string>;

interface FilterDef {
  key: FilterKey;
  /** The query parameter this control fills, and so the field the server
      reads. One name per filter, in one place. */
  param: keyof TokenListQuery;
  label: string;
  kind: "text" | "select" | "environment";
  placeholder?: string;
  options?: { value: string; label: string }[];
}

const FILTER_DEFS: FilterDef[] = [
  {
    // A searchable select, not a text box: the set of environments is known,
    // so picking one is both faster and exact. Typing "pro" would also match
    // a token id or an account id containing "pro".
    key: "env",
    param: "env_id",
    label: "Environment",
    kind: "environment",
  },
  {
    key: "tokenId",
    param: "token_id",
    label: "Token ID",
    kind: "text",
    // The whole id, not a fragment: an identifier is either the one that was
    // asked for or it is not (src/utils/searchMatch.js).
    placeholder: "Full token id",
  },
  {
    // The one column that narrows a list where everything else looks alike:
    // "show me the tokens Claude is using" or "the ones people created by
    // signing in". Matches the client name shown in the Token ID column.
    key: "client",
    param: "client",
    label: "Client",
    kind: "text",
    placeholder: "Client or agent name",
  },
  {
    key: "account",
    param: "account_id",
    label: "Account ID",
    kind: "text",
    placeholder: "Account id",
  },
  {
    key: "creator",
    param: "creator",
    label: "Generated by",
    kind: "text",
    placeholder: "Email or name",
  },
  {
    key: "access",
    param: "access",
    label: "Access",
    kind: "select",
    // The three states the Access badge can be in, so the filter and the
    // column it filters speak the same language. The server derives them from
    // the same summary the badge does.
    options: [
      { value: "", label: "Any access" },
      { value: "unrestricted", label: "Unrestricted" },
      { value: "restricted", label: "Restricted" },
      { value: "none", label: "No access" },
    ],
  },
  {
    key: "validity",
    param: "validity",
    label: "Validity",
    kind: "select",
    options: [
      { value: "", label: "Any validity" },
      { value: "expired", label: "Expired" },
      { value: "soon", label: `Expiring within ${EXPIRY_WARNING_DAYS} days` },
      { value: "valid", label: "Valid" },
      { value: "unknown", label: "No expiry recorded" },
    ],
  },
  {
    key: "updated",
    param: "updated",
    label: "Last updated",
    kind: "select",
    // A relative range rather than a date box: the column shows recency, and
    // typing an exact timestamp to find recent activity would be worse than
    // the ranges people actually ask for.
    options: [
      { value: "", label: "Any time" },
      { value: "24h", label: "Last 24 hours" },
      { value: "7d", label: "Last 7 days" },
      { value: "30d", label: "Last 30 days" },
      { value: "never", label: "Never updated" },
    ],
  },
  {
    key: "status",
    param: "status",
    label: "Status",
    kind: "select",
    options: [
      { value: "", label: "Any status" },
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
  },
];

export const EMPTY_FILTERS: TokenFilters = {
  env: "",
  tokenId: "",
  client: "",
  account: "",
  creator: "",
  access: "",
  validity: "",
  updated: "",
  status: "",
};

const FILTER_KEYS = Object.keys(EMPTY_FILTERS) as FilterKey[];

/** How long the search box waits after the last keystroke before asking the
    server. The same window CacheTable uses, for the same reason. */
const SEARCH_DEBOUNCE_MS = 350;

/** Filters, as the query the server understands. Blank controls are left out:
    an omitted parameter means "do not narrow by this", which is not the same
    request as sending an empty value (the server refuses those). */
export const toTokenListQuery = (
  filters: TokenFilters,
  search: string,
): TokenListQuery => {
  const query: TokenListQuery = {};

  for (const def of FILTER_DEFS) {
    const value = filters[def.key];
    if (value) query[def.param] = value;
  }

  if (search.trim()) query.search = search.trim();

  return query;
};

export interface TokensTableProps {
  /**
   * The rows the server returned for the applied filters. Already filtered:
   * this table never narrows them, because the client only ever holds the
   * response and a filter applied here would silently lie about the table.
   */
  tokens: AdminToken[];
  loading: boolean;
  /**
   * The filters the server was last asked for. The panel edits a draft of
   * these and hands the draft back through `onApplyFilters` when Done is
   * pressed, so nothing is fetched while a control is still being typed in.
   */
  filters: TokenFilters;
  onApplyFilters: (next: TokenFilters) => void;
  /**
   * The environment picker's options, from the server's unfiltered scope: the
   * filtered rows cannot produce them, or the picker would lose every
   * environment the current filter excludes.
   */
  environmentOptions: { id: string; name: string }[];
  /** True when the scope holds tokens with no environment, so the picker can
      offer "No environment" without inventing an option that matches nothing. */
  hasUnassigned: boolean;
  /** Rows in scope before filtering, for the footer and the empty state. */
  total: number;
  /** The search box, debounced by this table. Same reasoning as the filters:
      the server searches the scope, not the page that happens to be loaded. */
  onSearch: (term: string) => void;
  onPermissions: (token: AdminToken) => void;
  /**
   * Moves a token to its other status. The Status column draws a switch when
   * this is passed and a badge when it is not, which is how a caller without
   * the grant loses the control: the portal hands it over only for a user
   * holding api_tokens:update, and the server refuses the write again
   * (requirePortalPermission in src/routes/portal/apiTokens). The admin console
   * always passes it, because the whole console is the grant.
   *
   * Which route the OFF position reaches is `onDelete` below: this table has one
   * status lever and does not care which verb moves it.
   */
  onToggleStatus?: (token: AdminToken, next: boolean) => void | Promise<void>;
  /**
   * Opens the Activity Log page scoped to this token. The row action appears
   * only when this is passed: the admin console can do that, the portal can
   * too (its activity API takes a token filter), and a third caller with no
   * activity log to show simply leaves it out.
   */
  onActivityLogs?: (token: AdminToken) => void;
  /**
   * An environment the admin arrived here asking about, sent by the
   * Environments table's "View tokens" action. Applied to the environment
   * filter; a fresh object per click is what makes clicking the same
   * environment twice work after the filter was cleared in between.
   */
  envScope?: { id: string; name: string } | null;
  /** Tells the parent its scope is no longer applied. */
  onClearEnvScope?: () => void;
  /**
   * Called by the Status switch when a token goes out of service, by a caller
   * whose delete is a route of its own. The admin console does that: DELETE
   * /api/v1/admin/tokens/:id switches the token off and keeps its row. A caller
   * with no such endpoint, which includes the portal, falls back to the status
   * write for both positions.
   */
  onDelete?: (token: AdminToken) => void | Promise<void>;
}

export function TokensTable({
  tokens,
  loading,
  filters,
  onApplyFilters,
  environmentOptions,
  hasUnassigned,
  total,
  onSearch,
  onPermissions,
  onToggleStatus,
  onActivityLogs,
  envScope = null,
  onClearEnvScope,
  onDelete,
}: TokensTableProps) {
  /**
   * Switching a token off, through whichever route this caller has.
   *
   * Both directions hang off one grant, because they are one lever with two
   * positions: a caller trusted to take an integration out of service is the
   * same caller who has to be able to put it back. Splitting them across two
   * grants produced a state nobody could explain, a token that could be
   * switched off and never on.
   *
   * The Status switch is the ONLY control for that lever. The row menu used to
   * carry a second one, a Deactivate/Activate item calling the same two
   * endpoints, so every caller had two ways to do one thing and neither was
   * better than the other. The switch is the one that stays, because it shows
   * the current state as well as offering the other one.
   *
   * The portal reaches the status write for both positions, because its
   * api_tokens module has no delete grant and so no delete route; the admin
   * console sends the OFF position to DELETE /admin/tokens/:id, which is where
   * that verb lives. A caller with neither falls back to the status write.
   */
  const switchOff = (token: AdminToken) =>
    onDelete ? onDelete(token) : onToggleStatus?.(token, false);

  const columns = useMemo<ColumnDef<AdminToken>[]>(
    () => [
      {
        id: "env",
        header: "Environment",
        // Sorted by the name a reader sees, not by the uuid under it.
        accessor: (token) => token.environment_name,
        // The environment, the way the Environments table shows one: the name
        // it is called by, and the id it is identified by for support and for
        // the API. Two columns rather than one because a token is not "in" its
        // environment in the way a name suggests — the environment is a
        // separate thing that this token acts for, several tokens can act for
        // the same one, and a token can act for none at all.
        cell: (token) => (
          <div className="tok-name-cell">
            <div className="tok-name-row">
              <strong>
                {token.environment_name || <span className="text-muted">{EMPTY}</span>}
              </strong>
            </div>
            {token.env_id && (
              <div className="action-cell tok-id-row">
                <code className="tok-id-code">{token.env_id}</code>
                <CopyButton value={token.env_id} title="Copy environment ID" />
              </div>
            )}
          </div>
        ),
      },
      {
        id: "token",
        header: "Token ID",
        // Sorted by what the token was issued to rather than by its own id: a
        // uuid has no order worth reading, and "group the Claude tokens
        // together" is the question this column gets asked.
        accessor: (token) => token.client_name,
        // The token's own identity: the id its permissions are keyed on, and
        // what a caller quotes in a support ticket. Under it, what the token
        // was issued to and which Wrike account it acts in. Both ride along
        // here rather than taking columns of their own because a person can
        // hold several tokens in one environment and two of them can differ in
        // nothing else, so this is what tells the rows apart.
        cell: (token) => (
          <div className="tok-name-cell">
            <div className="action-cell tok-id-row">
              <code className="tok-id-code">{token.id}</code>
              <CopyButton value={token.id} title="Copy token ID" />
            </div>
            {(token.client_name || token.account_id) && (
              <div className="tok-name-row">
                {token.client_name && (
                  <span className="tok-client" title="Issued to">
                    {token.client_name}
                  </span>
                )}
                {token.account_id && (
                  // Labelled rather than shown bare: with no column header of
                  // its own, a bare number beside a client name does not say
                  // what it is. Styled as a reference chip (see TokensTable.css)
                  // so it reads as separate from the two names above it.
                  <span className="tok-account" title="Wrike account">
                    <span className="tok-account-label">Acct</span>
                    <span className="tok-account-code">{token.account_id}</span>
                  </span>
                )}
              </div>
            )}
          </div>
        ),
      },
      {
        id: "creator",
        header: "Generated By",
        accessor: (token) => token.creator_email,
        cell: (token) =>
          token.creator_email ? (
            <div className="tok-creator">
              <span>{token.creator_email}</span>
              {token.creator_name && (
                <span className="tok-creator-name">{token.creator_name}</span>
              )}
            </div>
          ) : (
            <span className="text-muted">{EMPTY}</span>
          ),
      },
      {
        id: "access",
        header: "Access",
        // Sorts on the number granted, so the most restricted tokens group
        // together instead of the alphabetical order of their labels. A token
        // nobody has restricted is summarised as fully granted, so it sorts
        // with full access rather than at zero.
        accessor: (token) => token.permissions.granted,
        cell: (token) => {
          const state = accessStateOf(token.permissions);
          const { granted, total } = token.permissions;
          const { tone, icon } = ACCESS_BADGE[state];

          return (
            // Badge has no title prop, and the difference between a token that
            // was never restricted and one that was granted everything is a
            // fact about its history, not its access, so it lives here.
            <span title={accessDetail(token.permissions)}>
              <Badge tone={tone} icon={icon}>
                {accessLabel(state, granted, total)}
              </Badge>
            </span>
          );
        },
      },
      {
        id: "validity",
        header: "Validity",
        // Sorts on the expiry itself, so whatever is closest to breaking sits
        // at the top of the list.
        accessor: (token) => dateSortValue(token.token_expires_at),
        cell: (token) => {
          const validity = validityOf(token.token_expires_at);
          return (
            // Badge has no title prop, and the exact timestamp is what an
            // admin needs once the label tells them a token is worth a look.
            <span title={validity.detail}>
              <Badge tone={validity.tone}>{validity.label}</Badge>
            </span>
          );
        },
      },
      {
        id: "is_active",
        header: "Status",
        width: "92px",
        sortable: false,
        /* The only control for a token's status, both directions, and the only
           one its grant has to cover (see switchOff above). A caller that hands
           this table no writer gets the state as a badge instead: no switch is
           drawn, and the server refuses the write anyway. */
        cell: (token) =>
          onToggleStatus ? (
            <Toggle
              size="sm"
              checked={token.is_active}
              title={
                token.is_active
                  ? "Deactivate this token"
                  : "Reactivate this token"
              }
              ariaLabel={`Status for token ${token.id}`}
              onToggle={(next) =>
                next ? onToggleStatus(token, true) : switchOff(token)
              }
            />
          ) : (
            // Read-only for this direction: the state is still worth showing,
            // it just is not theirs to change. A switch that silently does
            // nothing would be worse than a badge that says what is true.
            <Badge tone={token.is_active ? "success" : "danger"} dot>
              {token.is_active ? "Active" : "Off"}
            </Badge>
          ),
      },
      {
        id: "actions",
        header: "Actions",
        width: "64px",
        align: "center",
        className: "tok-actions-col",
        headerClassName: "tok-actions-col",
        // No power item: a token's status belongs to the Status column's switch
        // and nowhere else (see switchOff above).
        cell: (token) => (
          <RowMenu
            label={`Actions for token ${token.id}`}
            items={[
              {
                // Shown to anyone who can see this table at all, which means
                // read. Whether it can be changed is the popup's business
                // (it takes readOnly), because "you may not edit this" and
                // "you may not look at this" are different answers, and a
                // reader with no way to open the matrix has to guess what a
                // token can do. The write is refused server-side regardless.
                label: "Permissions",
                icon: "fa-solid fa-shield-halved",
                onSelect: () => onPermissions(token),
              },
              ...(onActivityLogs
                ? [
                    {
                      label: "Activity logs",
                      icon: "fa-solid fa-clock-rotate-left",
                      onSelect: () => onActivityLogs(token),
                    },
                  ]
                : []),
              {
                label: "Copy token ID",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  navigator.clipboard?.writeText(token.id).catch(() => {});
                },
              },
              {
                // The account number is in the Token ID column, small and under
                // the token's own id, so this is how a caller copies the value
                // the Account filter above expects rather than selecting 11px
                // text out of a dense cell.
                label: "Copy account ID",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  if (token.account_id) {
                    navigator.clipboard?.writeText(token.account_id).catch(() => {});
                  }
                },
              },
              {
                // The username is the value a caller authenticates with and it
                // is no longer a column (it repeats the account id, the
                // environment and the email), so it stays reachable here.
                label: "Copy username",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  if (token.username) {
                    navigator.clipboard?.writeText(token.username).catch(() => {});
                  }
                },
              },
            ]}
          />
        ),
      },
    ],
    [onPermissions, onToggleStatus, onActivityLogs, onDelete],
  );

  /**
   * The panel's own copy of the filters, which is what the inputs edit.
   *
   * Separate from `filters` (the applied set the parent fetched with) so that
   * a half-typed account id is not a query, and so the table keeps showing one
   * thing while the panel holds another. Done commits; nothing else does.
   */
  const [draft, setDraft] = useState<TokenFilters>(filters);
  const [filtersOpen, setFiltersOpen] = useState(false);

  // The draft follows the applied filters whenever they change from outside:
  // the Environments table's "View tokens" scope, or a Clear in the empty
  // state. Without this the panel would reopen showing what was typed last
  // rather than what the table is actually showing.
  useEffect(() => {
    setDraft(filters);
  }, [filters]);

  // Fixed-position coordinates for the portalled popup, measured from the
  // button when it opens (null until then).
  const [popupPosition, setPopupPosition] = useState<{ top: number; left: number } | null>(
    null,
  );
  const filterButtonRef = useRef<HTMLButtonElement>(null);
  const popupRef = useRef<HTMLDivElement>(null);

  // Below this width the popup stops being a floating panel and becomes a
  // bottom sheet. A 460px panel on a 360px viewport is unusable either way.
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const query = window.matchMedia("(max-width: 640px)");
    const sync = () => setIsMobile(query.matches);
    sync();
    query.addEventListener("change", sync);
    return () => query.removeEventListener("change", sync);
  }, []);

  const setFilter = (key: FilterKey, value: string) =>
    setDraft((prev) => ({ ...prev, [key]: value }));

  /** What the table is showing, not what the panel currently says. */
  const activeFilterCount = Object.values(filters).filter(Boolean).length;

  /** True when Done would change the request, which is what the footer says. */
  const dirty = FILTER_KEYS.some((key) => draft[key] !== filters[key]);

  const applyDraft = () => {
    onApplyFilters(draft);
    setFiltersOpen(false);
  };

  // The applied filters as they are right now, for callbacks that must not be
  // re-created (and must not re-run) every time they change.
  const appliedRef = useRef(filters);
  appliedRef.current = filters;

  // The Environments table's "View tokens" action lands here, so the
  // environment filter has to follow it — and it applies immediately, because
  // arriving from an environment row *is* the request. Only the environment
  // filter is touched: that should not silently drop a filter the admin had
  // already set by hand.
  const lastScopeRef = useRef<string | null>(null);
  useEffect(() => {
    const id = envScope ? envScope.id : "";
    if (lastScopeRef.current === id) return;
    lastScopeRef.current = id;

    const next = { ...appliedRef.current, env: id };
    if (next.env === appliedRef.current.env) return;
    onApplyFilters(next);
  }, [envScope, onApplyFilters]);

  // A new result set is a new question, so it opens on its first page. useTable
  // clamps the page when the list shrinks, which is the wrong answer here:
  // page 3 of the old result is not page 3 of the new one.

  // The picker's options, from the server's unfiltered scope. Built here
  // rather than fetched separately so the label the chip shows and the option
  // the select offers come from one list.
  const pickerOptions = useMemo(() => {
    const options = [
      { value: "", label: "All environments" },
      ...environmentOptions.map(({ id, name }) => ({ value: id, label: name })),
    ];

    if (hasUnassigned) {
      options.push({ value: NO_ENVIRONMENT, label: "No environment" });
    }

    return options;
  }, [environmentOptions, hasUnassigned]);

  // The chip beside the Filters button names whatever environment filter is
  // applied, whether it came from the Environments table or from the popup, so
  // "why is this list short?" always has an answer on screen. Resolved through
  // the same option list the picker uses, so the two can never disagree; the
  // scope's own name is the fallback for an environment that holds no tokens
  // yet and therefore has no option.
  const scopeLabel = filters.env
    ? pickerOptions.find((option) => option.value === filters.env)?.label ||
      (envScope?.id === filters.env ? envScope.name : null) ||
      filters.env
    : null;

  // Esc closes the filter popup, like every other popup in the console.
  const closeFilters = useCallback(() => {
    setFiltersOpen(false);
    setPopupPosition(null);
  }, []);

  useEffect(() => {
    if (!filtersOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") closeFilters();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [filtersOpen, closeFilters]);

  // Clicking anywhere outside closes it. A pointerdown listener rather than a
  // full-screen scrim, because the popup is portalled onto <body> and a scrim
  // there would swallow the click before AdminSelect's own panel saw it.
  useEffect(() => {
    if (!filtersOpen) return;
    const onPointerDown = (event: PointerEvent) => {
      const target = event.target as Node;
      if (popupRef.current?.contains(target)) return;
      if (filterButtonRef.current?.contains(target)) return;
      closeFilters();
    };
    document.addEventListener("pointerdown", onPointerDown);
    return () => document.removeEventListener("pointerdown", onPointerDown);
  }, [filtersOpen, closeFilters]);

  /* Measure after paint but before the browser shows the frame, so the popup
     never appears at the wrong spot for one frame, the same approach as RowMenu,
     which portals its menu for the same reason. Right-aligned to the button so
     it opens under the control that owns it, and flipped above when it would
     run off the bottom of the window. */
  useLayoutEffect(() => {
    // Nothing to measure on mobile: the sheet is pinned to the bottom of the
    // viewport by its own styles.
    if (!filtersOpen || isMobile) return;
    const trigger = filterButtonRef.current;
    const popup = popupRef.current;
    if (!trigger || !popup) return;

    const anchor = trigger.getBoundingClientRect();
    const { width, height } = popup.getBoundingClientRect();
    const edge = 8;

    let left = anchor.right - width;
    left = Math.max(edge, Math.min(left, window.innerWidth - width - edge));

    let top = anchor.bottom + 6;
    if (top + height > window.innerHeight - edge) {
      top = Math.max(edge, anchor.top - height - 6);
    }

    setPopupPosition({ top, left });
  }, [filtersOpen, isMobile]);

  // The rows are already what the server decided, so the table sorts and pages
  // them and does not search them: clientSearch is off, and the search box is
  // handed to the server below. A search applied here would only ever cover the
  // rows this response happened to contain.
  const table = useTable({
    data: tokens,
    columns,
    getRowId: (token) => token.id,
    initialPageSize: 10,
    clientSearch: false,
  });

  const { search, setPage } = table;

  // A new result set is a new question, so it opens on its first page. useTable
  // clamps the page when the list shrinks, which is the wrong answer here:
  // page 3 of the old result is not page 3 of the new one.
  useEffect(() => {
    setPage(1);
  }, [filters, setPage]);

  /* The search box, on a timer. Typing "prod" is one request rather than four,
     and the term that is sent is the term that was settled on rather than every
     prefix of it. Same shape as CacheTable's debounce, for the same reason. */
  useEffect(() => {
    const timer = window.setTimeout(
      () => onSearch(search.trim()),
      SEARCH_DEBOUNCE_MS,
    );
    return () => window.clearTimeout(timer);
  }, [search, onSearch]);

  // Rendered into the DataTable toolbar slot, which puts it immediately to the
  // right of the search box. The filters themselves open in a popup rather
  // than sitting permanently above the table: the default view of this page is
  // the table, not a form.
  const filterControl = (
    <div className="tok-filter-wrap">
      <button
        ref={filterButtonRef}
        type="button"
        className={`tok-filter-toggle${filtersOpen ? " is-open" : ""}`}
        aria-expanded={filtersOpen}
        aria-haspopup="dialog"
        onClick={() => (filtersOpen ? closeFilters() : setFiltersOpen(true))}
      >
        <i className="fa-solid fa-filter" aria-hidden="true" />
        Filters
        {activeFilterCount > 0 && (
          <span className="tok-filter-count">{activeFilterCount}</span>
        )}
      </button>

      {scopeLabel && (
        <span className="tok-scope-chip" title={`Showing tokens for ${scopeLabel} only`}>
          <i className="fa-solid fa-layer-group" aria-hidden="true" />
          <span className="tok-scope-chip-label">{scopeLabel}</span>
          <button
            type="button"
            className="tok-scope-chip-clear"
            onClick={() => {
              // Arrived from an environment row? The parent owns that scope, and
              // clearing it re-applies the filter through the effect above, so
              // this is one request rather than two. Otherwise the filter came
              // from the panel and is cleared here, applied immediately: a chip
              // that stays on screen until Done would be lying about the table.
              if (envScope) {
                onClearEnvScope?.();
                return;
              }

              const next = { ...draft, env: "" };
              setDraft(next);
              onApplyFilters(next);
            }}
            aria-label="Clear the environment filter"
            title="Clear the environment filter"
          >
            <i className="fa-solid fa-xmark" aria-hidden="true" />
          </button>
        </span>
      )}

      {/* Portalled onto <body>: this table sits inside a .card, which clips
          its own overflow for the rounded corners, so an absolutely-positioned
          panel would be cut off at the card's edge. RowMenu portals its menu
          for exactly this reason. */}
      {filtersOpen &&
        createPortal(
          <>
            {isMobile && (
              <div
                className="tok-filter-backdrop"
                aria-hidden="true"
                onClick={closeFilters}
              />
            )}

            <div
              ref={popupRef}
              className={`tok-filter-popup${isMobile ? " tok-filter-sheet" : ""}`}
              role="dialog"
              aria-modal={isMobile || undefined}
              aria-label="Filter tokens"
              style={
                isMobile
                  ? undefined
                  : popupPosition
                    ? { top: popupPosition.top, left: popupPosition.left }
                    : // Measured in a layout effect the moment it mounts;
                      // hidden until then so it never flashes in the corner.
                      { top: 0, left: 0, visibility: "hidden" }
              }
            >
              {/* Sheet affordance. Hidden above the mobile breakpoint. */}
              <div className="tok-filter-sheet-handle" aria-hidden="true" />
            <div className="tok-filter-popup-head">
              <span className="tok-filter-popup-title">
                <i className="fa-solid fa-filter" aria-hidden="true" />
                Filter tokens
              </span>
              <button
                type="button"
                className="tok-filter-popup-close"
                aria-label="Close filters"
                onClick={closeFilters}
              >
                <i className="fa-solid fa-xmark" aria-hidden="true" />
              </button>
            </div>

            <div className="tok-filter-popup-body">
              {FILTER_DEFS.map((def) => (
                <div className="tok-filter-field" key={def.key}>
                  <div className="tok-filter-labelrow">
                    <label className="tok-filter-label" htmlFor={`tok-filter-${def.key}`}>
                      {def.label}
                    </label>
                    {/* Per-field clear, so undoing one choice does not mean
                        undoing every other one to do it. */}
                    {draft[def.key] ? (
                      <button
                        type="button"
                        className="tok-filter-fieldclear"
                        onClick={() => setFilter(def.key, "")}
                        aria-label={`Clear the ${def.label.toLowerCase()} filter`}
                        title="Clear this filter"
                      >
                        <i className="fa-solid fa-xmark" aria-hidden="true" />
                      </button>
                    ) : null}
                  </div>
                  {def.kind === "text" ? (
                    <input
                      id={`tok-filter-${def.key}`}
                      className="form-control"
                      type="text"
                      value={draft[def.key]}
                      placeholder={def.placeholder}
                      autoComplete="off"
                      onChange={(e) => setFilter(def.key, e.target.value)}
                    />
                  ) : (
                    <AdminSelect
                      id={`tok-filter-${def.key}`}
                      ariaLabel={`Filter by ${def.label.toLowerCase()}`}
                      value={draft[def.key]}
                      onChange={(value) => setFilter(def.key, value)}
                      // The environment list is the long one, so it keeps the
                      // type-to-narrow search; a three-state list is shorter
                      // than the search box would be.
                      searchable={def.kind === "environment"}
                      options={
                        def.kind === "environment" ? pickerOptions : def.options || []
                      }
                    />
                  )}
                </div>
              ))}
            </div>

            {/* The count is the server's, not a filter applied here: it says
                how many rows matched out of the scope, and while the panel
                holds uncommitted changes it says so instead of promising a
                number nothing has computed yet. */}
            <div className="tok-filter-popup-foot">
              <span className="tok-filter-popup-count" aria-live="polite">
                {dirty
                  ? "Not applied yet"
                  : `${tokens.length} of ${total} token${total === 1 ? "" : "s"}`}
              </span>
              <div className="tok-filter-popup-actions">
                <button
                  type="button"
                  className="btn btn-ghost"
                  onClick={() => setDraft(EMPTY_FILTERS)}
                  disabled={FILTER_KEYS.every((key) => !draft[key])}
                >
                  Clear all
                </button>
                <button
                  type="button"
                  className={`btn btn-primary${dirty ? " tok-filter-apply" : ""}`}
                  onClick={applyDraft}
                >
                  Done
                </button>
              </div>
            </div>
          </div>,
          </>,
          document.body,
        )}
    </div>
  );

  return (
    <DataTable
      table={table}
      caption="Sessions"
      loading={loading}
      className="tok-table"
      searchPlaceholder="Search by name, account, user or id…"
      toolbar={filterControl}
        empty={
          activeFilterCount > 0 ? (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-filter" aria-hidden="true" />
              </div>
              <h3>No tokens match those filters</h3>
              <p>
                {total} token{total === 1 ? "" : "s"} in scope, and none of them match
                every filter applied.
              </p>
              <button
                type="button"
                className="btn btn-primary"
                // Clears and applies in one press: this button is outside the
                // panel, so there is no Done to wait for.
                onClick={() => {
                  setDraft(EMPTY_FILTERS);
                  onApplyFilters(EMPTY_FILTERS);
                }}
              >
                <i className="fa-solid fa-xmark" aria-hidden="true" /> Clear filters
              </button>
            </div>
          ) : (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-key" aria-hidden="true" />
              </div>
              <h3>No tokens yet</h3>
              <p>
                Tokens appear here as soon as a user generates one from the environment login
                page.
              </p>
            </div>
          )
        }
      />
  );
}
