// Merged custom fields IDs and shortcodes as a pure JSON object

export const test = {
  "CopyToChild*": { id: "IEABCEFLJUAEF4SP", shortcode: "copytochild" },
  "Client*": { id: "IEABCEFLJUAEF4AK", shortcode: "client" },
  "Debtor*": { id: "IEABCEFLJUAEGGC3", shortcode: "debtor" },
  "Campaign Name*": { id: "IEABCEFLJUAEF4AO", shortcode: "campaignname" },
  "URL*": { id: "IEABCEFLJUAGLJUS", shortcode: "url" },
  "Space Name*": { id: "IEABCEFLJUAEF4SQ", shortcode: "spacename" },
  "CampaignFeedbackStatus*": {
    id: "IEABCEFLJUAGCXYP",
    shortcode: "campaignfeedbackstatus",
  },
  "Feedback-Ref-ID": { id: "IEABCEFLJUAGCSMH", shortcode: "feedbackrefid" },
  "WrikeXPI-State": { id: "IEABCEFLJUAGPAMB", shortcode: "wrikexpistate" },
  "Agency*": { id: "IEABCEFLJUAEF4AI", shortcode: "agency" },
  "Campaign Start Date*": {
    id: "IEABCEFLJUAEF4BI",
    shortcode: "campaignstartdate",
  },
  "Campaign End Date*": {
    id: "IEABCEFLJUAEF4BJ",
    shortcode: "campaignenddate",
  },
  "Currency*": { id: "IEABCEFLJUAEGPM6", shortcode: "currency" },
  "Campaign Objective*": {
    id: "IEABCEFLJUAEF4B7",
    shortcode: "campaignobjective",
  },
  "Brand*": { id: "IEABCEFLJUAEF4AJ", shortcode: "brand" },
  "Requestor's Market*": {
    id: "IEABCEFLJUAEF4AM",
    shortcode: "requestormarket",
  },
  "CCUID*": { id: "IEABCEFLJUAGCS2I", shortcode: "ccuid" },
  "CSSID*": { id: "IEABCEFLJUAGCS2J", shortcode: "cssid" },
  "ReadyForArchive*": { id: "", shortcode: "readyforarchive" },
  "Region*": { id: "", shortcode: "region" },
  "Work Item Level": { id: "", shortcode: "workitemlevel" },
  "Original Agency*": { id: "", shortcode: "originalagency" },
  "KPI Objective*": { id: "", shortcode: "kpiobjective" },
  Currency: { id: "", shortcode: "currency" },
  "CampaignFeedbackStatus*": { id: "", shortcode: "campaignfeedbackstatus" },
  "Briefed Date*": { id: "", shortcode: "briefeddate" },
  "Campaign Budget*": { id: "", shortcode: "campaignbudget" },
  "Campaign ID*": { id: "", shortcode: "campaignid" },
  "# CRs": { id: "", shortcode: "noofcrs" },
  "Biddable/Non-Biddable*": { id: "", shortcode: "mediabuyingtype" },
  "Channel/Practice*": { id: "", shortcode: "mediachannelpractice" },
  "Comments*": { id: "", shortcode: "comments" },
  "PO Number": { id: "", shortcode: "customerponumber" },
};
export const live = {
  "CopyToChild*": { id: "IEAC7PRTJUADKV3A", shortcode: "copytochild" },
  "Client*": { id: "IEAC7PRTJUAB43DH", shortcode: "client" },
  "Debtor*": { id: "IEAC7PRTJUAB72M2", shortcode: "debtor" },
  "Campaign Name*": { id: "IEAC7PRTJUAB43EK", shortcode: "campaignname" },
  "URL*": { id: "IEAC7PRTJUADKX7R", shortcode: "url" },
  "Space Name*": { id: "IEAC7PRTJUADKWAW", shortcode: "spacename" },
  "CampaignFeedbackStatus*": {
    id: "IEAC7PRTJUAEGVJ6",
    shortcode: "campaignfeedbackstatus",
  },
  "Feedback-Ref-ID": { id: "IEAC7PRTJUAEGKBO", shortcode: "feedbackrefid" },
  "WrikeXPI-State": { id: "IEAC7PRTJUAGPA6B", shortcode: "wrikexpistate" },
  "Agency*": { id: "IEAC7PRTJUAB43DB", shortcode: "agency" },
  "Campaign Start Date*": {
    id: "IEAC7PRTJUAB5IHK",
    shortcode: "campaignstartdate",
  },
  "Campaign End Date*": {
    id: "IEAC7PRTJUAB5IHL",
    shortcode: "campaignenddate",
  },
  "Currency*": { id: "IEAC7PRTJUAB5BLC", shortcode: "currency" },
  "Campaign Objective*": {
    id: "IEAC7PRTJUAB7P4W",
    shortcode: "campaignobjective",
  },
  "Brand*": { id: "IEAC7PRTJUAB43DE", shortcode: "brand" },
  "Requestor's Market*": {
    id: "IEAC7PRTJUAB43DP",
    shortcode: "requestormarket",
  },
  "Requested Start Date*": {
    id: "IEAC7PRTJUAB7RBO",
    shortcode: "requestedstartdate",
  },
  "CCUID*": { id: "IEAC7PRTJUAEF7QO", shortcode: "ccuid" },
  "CSSID*": { id: "IEAC7PRTJUAEGSYH", shortcode: "cssid" },
  "ReadyForArchive*": {
    id: "IEAC7PRTJUAFY5EA",
    shortcode: "readyforarchive",
  },
  "Region*": { id: "IEAC7PRTJUAB432Y", shortcode: "region" },
  "Work Item Level": { id: "IEAC7PRTJUADKWPE", shortcode: "workitemlevel" },
  "Original Agency*": { id: "IEAC7PRTJUAG6BDW", shortcode: "originalagency" },
  "KPI Objective*": { id: "IEAC7PRTJUAB7TUM", shortcode: "kpiobjective" },
  Currency: { id: "IEAC7PRTJUAHYJLK", shortcode: "currency" },
  "CampaignFeedbackStatus*": {
    id: "IEAC7PRTJUAEGVJ6",
    shortcode: "campaignfeedbackstatus",
  },
  "Briefed Date*": { id: "IEAC7PRTJUAEGO3E", shortcode: "briefeddate" },
  "Campaign Budget*": { id: "IEAC7PRTJUACLFZ7", shortcode: "campaignbudget" },
  "Campaign ID*": { id: "IEAC7PRTJUAEGPF7", shortcode: "campaignid" },
  "# CRs": { id: "IEAC7PRTJUAB5SNG", shortcode: "noofcrs" },
  "Biddable/Non-Biddable*": {
    id: "IEAC7PRTJUAGPDRE",
    shortcode: "mediabuyingtype",
  },
  "Channel/Practice*": {
    id: "IEAC7PRTJUAB5SNE",
    shortcode: "mediachannelpractice",
  },
  "Comments*": { id: "IEAC7PRTJUABQSTP", shortcode: "comments" },
  "PO Number": { id: "IEAC7PRTJUABDEC7", shortcode: "customerponumber" },
};
