const shortcodes = {
  noofcrs: "# CRs",
  agency: "Agency*",
  mediabuyingtype: "Biddable/Non-Biddable*",
  brand: "Brand*",
  briefeddate: "Briefed Date*",
  campaignbudget: "Campaign Budget*",
  campaignenddate: "Campaign End Date*",
  campaignid: "Campaign ID*",
  campaignname: "Campaign Name*",
  campaignobjective: "Campaign Objective*",
  campaignstartdate: "Campaign Start Date*",
  campaignfeedbackstatus: "CampaignFeedbackStatus*",
  ccuid: "CCUID*",
  mediachannelpractice: "Channel/Practice*",
  client: "Client*",
  comments: "Comments*",
  cssid: "CSSID*",
  currency: "Currency",
  customerponumber: "PO Number",
  debtor: "Debtor*",
  kpiobjective: "KPI Objective*",
  originalagency: "Original Agency*",
  readyforarchive: "ReadyForArchive*",
  region: "Region*",
  requestedstartdate: "Requested Start Date*",
  requestormarket: "Requestor's Market*",
  spacename: "Space Name*",
  workitemlevel: "Work Item Level",
};

function transform(obj) {
  const result = {};
  Object.entries(obj).forEach(([key, value]) => {
    let shortcode = Object.keys(shortcodes).find(
      (sc) => shortcodes[sc] === key
    );
    if (!shortcode) shortcode = key.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    result[key] = { id: value, shortcode };
  });
  return result;
}

module.exports = {
  test: transform({
    "CopyToChild*": "IEABCEFLJUAEF4SP",
    "Client*": "IEABCEFLJUAEF4AK",
    "Debtor*": "IEABCEFLJUAEGGC3",
    "Campaign Name*": "IEABCEFLJUAEF4AO",
    "URL*": "IEABCEFLJUAGLJUS",
    "Space Name*": "IEABCEFLJUAEF4SQ",
    "CampaignFeedbackStatus*": "IEABCEFLJUAGCXYP",
    "Feedback-Ref-ID": "IEABCEFLJUAGCSMH",
    "WrikeXPI-State": "IEABCEFLJUAGPAMB",
    "Agency*": "IEABCEFLJUAEF4AI",
    "Campaign Start Date*": "IEABCEFLJUAEF4BI",
    "Campaign End Date*": "IEABCEFLJUAEF4BJ",
    "Currency*": "IEABCEFLJUAEGPM6",
    "Campaign Objective*": "IEABCEFLJUAEF4B7",
    "Brand*": "IEABCEFLJUAEF4AJ",
    "Requestor's Market*": "IEABCEFLJUAEF4AM",
    "CCUID*": "IEABCEFLJUAGCS2I",
    "CSSID*": "IEABCEFLJUAGCS2J",
    "ReadyForArchive*": "",
    "Region*": "",
    "Work Item Level": "",
    "Original Agency*": "",
    "KPI Objective*": "",
    Currency: "",
    "CampaignFeedbackStatus*": "",
    "Briefed Date*": "",
    "Campaign Budget*": "",
    "Campaign ID*": "",
    "# CRs": "",
    "Biddable/Non-Biddable*": "",
    "Channel/Practice*": "",
    "Comments*": "",
    "PO Number": "",
  }),
  live: transform({
    "CopyToChild*": "IEAC7PRTJUADKV3A",
    "Client*": "IEAC7PRTJUAGPHMQ",
    "Debtor*": "IEAC7PRTJUAB72M2",
    "Campaign Name*": "IEAC7PRTJUAB43EK",
    "URL*": "IEAC7PRTJUADKX7R",
    "Space Name*": "IEAC7PRTJUADKWAW",
    "CampaignFeedbackStatus*": "IEAC7PRTJUAEGVJ6",
    "Feedback-Ref-ID": "IEAC7PRTJUAEGKBO",
    "WrikeXPI-State": "IEAC7PRTJUAGPA6B",
    "Agency*": "IEAC7PRTJUAB43DB",
    "Campaign Start Date*": "IEAC7PRTJUAB5IHK",
    "Campaign End Date*": "IEAC7PRTJUAB5IHL",
    "Currency*": "IEAC7PRTJUAB5BLC",
    "Campaign Objective*": "IEAC7PRTJUAB7P4W",
    "Brand*": "IEAC7PRTJUAB43DE",
    "Requestor's Market*": "IEAC7PRTJUAB43DP",
    "Requested Start Date*": "IEAC7PRTJUAB7RBO",
    "CCUID*": "IEAC7PRTJUAEF7QO",
    "CSSID*": "IEAC7PRTJUAEGSYH",
    "ReadyForArchive*": "IEAC7PRTJUAFY5EA",
    "Region*": "IEAC7PRTJUAB432Y",
    "Work Item Level": "IEAC7PRTJUADKWPE",
    "Original Agency*": "IEAC7PRTJUAG6BDW",
    "KPI Objective*": "IEAC7PRTJUAB7TUM",
    Currency: "IEAC7PRTJUAHYJLK",
    "CampaignFeedbackStatus*": "IEAC7PRTJUAEGVJ6",
    "Briefed Date*": "IEAC7PRTJUAEGO3E",
    "Campaign Budget*": "IEAC7PRTJUACLFZ7",
    "Campaign ID*": "IEAC7PRTJUAEGPF7",
    "# CRs": "IEAC7PRTJUAB5SNG",
    "Biddable/Non-Biddable*": "IEAC7PRTJUAGPDRE",
    "Channel/Practice*": "IEAC7PRTJUAB5SNE",
    "Comments*": "IEAC7PRTJUABQSTP",
    "PO Number": "IEAC7PRTJUABDEC7",
  }),
};
