import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { createPortal } from "react-dom";
import type { AdminToken } from "../../lib/tokenPermissionsApi";
import { DataTable } from "../../components/ui/DataTable";
import { useTable, type ColumnDef } from "../../components/ui/useTable";
import { RowMenu } from "../../components/ui/RowMenu";
import { CopyButton } from "../../components/ui/CopyButton";
import { Toggle } from "../../components/ui/Toggle";
import { Badge, type BadgeTone } from "../../components/ui/Badge";
import AdminSelect from "../../components/AdminSelect";
import { EMPTY, dateSortValue, formatDateTime } from "../../lib/format";
import "./TokensTable.css";

/* The API Tokens table: one row per token record the token service has
 * issued, with the module permissions that govern it reachable from the row
 * itself (the modal is owned by AdminDashboard, exactly as the portal-user
 * permissions modal is).
 *
 * The row deliberately shows the token's *identity* (which environment and
 * account it acts for, which Wrike user generated it, and what it is allowed
 * to do) and never the credential it carries. An admin who needs the token
 * value uses the console's token tooling; this screen can't leak it because
 * the API never sends it. */

/* ── Advanced filters ─────────────────────────────────────────────────
   The table's own search box is one substring over the whole row; this is
   the per-column version of it, one control per column that can meaningfully
   be narrowed (every column except Actions, which is a menu).

   The definitions below are the single authority: they render the controls
   and they decide what each control matches, so a filter can never be
   displayed without being applied or applied without being displayed. */

type FilterKey =
  | "env"
  | "tokenId"
  | "client"
  | "account"
  | "creator"
  | "access"
  | "validity"
  | "updated"
  | "status";

interface FilterDef {
  key: FilterKey;
  label: string;
  kind: "text" | "select" | "environment";
  placeholder?: string;
  options?: { value: string; label: string }[];
}

/** Option value standing for "tokens that are not attached to an environment". */
const NO_ENVIRONMENT = "\u0000none";

/** Days before expiry at which a token is worth flagging: enough notice to
    re-authenticate before whatever is using it starts failing. */
const EXPIRY_WARNING_DAYS = 14;

const MS_PER_DAY = 24 * 60 * 60 * 1000;

const FILTER_DEFS: FilterDef[] = [
  {
    // A searchable select, not a text box: the set of environments is known,
    // so picking one is both faster and exact. Typing "pro" would also match
    // a token id or an account id containing "pro".
    key: "env",
    label: "Environment",
    kind: "environment",
  },
  {
    key: "tokenId",
    label: "Token ID",
    kind: "text",
    placeholder: "Full or partial id",
  },
  {
    // The one column that narrows a list where everything else looks alike:
    // "show me the tokens Claude is using" or "the ones people created by
    // signing in". Matches the client name shown in the Token column.
    key: "client",
    label: "Client",
    kind: "text",
    placeholder: "Client or agent name",
  },
  { key: "account", label: "Account ID", kind: "text", placeholder: "Account id" },
  { key: "creator", label: "Generated by", kind: "text", placeholder: "Email or name" },
  {
    key: "access",
    label: "Access",
    kind: "select",
    // The three states the Access badge can be in, so the filter and the
    // column it filters speak the same language.
    options: [
      { value: "", label: "Any access" },
      { value: "unrestricted", label: "Unrestricted" },
      { value: "restricted", label: "Restricted" },
      { value: "none", label: "No access" },
    ],
  },
  {
    key: "validity",
    label: "Validity",
    kind: "select",
    options: [
      { value: "", label: "Any validity" },
      { value: "expired", label: "Expired" },
      { value: "soon", label: `Expiring within ${EXPIRY_WARNING_DAYS} days` },
      { value: "valid", label: "Valid" },
      { value: "unknown", label: "No expiry recorded" },
    ],
  },
  {
    key: "updated",
    label: "Last updated",
    kind: "select",
    // A relative range rather than a date box: the column shows recency, and
    // typing an exact timestamp to find recent activity would be worse than
    // the ranges people actually ask for.
    options: [
      { value: "", label: "Any time" },
      { value: "24h", label: "Last 24 hours" },
      { value: "7d", label: "Last 7 days" },
      { value: "30d", label: "Last 30 days" },
      { value: "never", label: "Never updated" },
    ],
  },
  {
    key: "status",
    label: "Status",
    kind: "select",
    options: [
      { value: "", label: "Any status" },
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
  },
];

const EMPTY_FILTERS: Record<FilterKey, string> = {
  env: "",
  tokenId: "",
  client: "",
  account: "",
  creator: "",
  access: "",
  validity: "",
  updated: "",
  status: "",
};

const RANGE_MS: Record<string, number> = {
  "24h": 24 * 60 * 60 * 1000,
  "7d": 7 * 24 * 60 * 60 * 1000,
  "30d": 30 * 24 * 60 * 60 * 1000,
};

interface Validity {
  tone: BadgeTone;
  label: string;
  detail: string;
}

/**
 * How long the token a caller holds will keep working.
 *
 * Two different things can stop a token: an admin switching it off (the Status
 * column) and its own expiry. This is only the second one, and it is a fact
 * about the credential rather than a setting, which is why it does not read as
 * a warning unless it is close.
 */
const validityOf = (token: AdminToken): Validity => {
  if (!token.token_expires_at) {
    return {
      tone: "neutral",
      label: "Unknown",
      detail: "No expiry was recorded for this token. It is checked when a caller uses it.",
    };
  }

  const expiresAt = new Date(token.token_expires_at).getTime();
  const days = Math.floor((expiresAt - Date.now()) / MS_PER_DAY);
  const when = formatDateTime(token.token_expires_at);

  if (days < 0) {
    return {
      tone: "danger",
      label: "Expired",
      detail: `Expired ${when}. Callers are refused until they sign in again.`,
    };
  }

  if (days <= EXPIRY_WARNING_DAYS) {
    return {
      tone: "warning",
      label: days === 0 ? "Expires today" : `${days} day${days === 1 ? "" : "s"} left`,
      detail: `Expires ${when}.`,
    };
  }

  return { tone: "neutral", label: `${days} days left`, detail: `Expires ${when}.` };
};

/**
 * The three states the Access column can be in, decided in one place so the
 * badge, the filter over it and the sort can never disagree.
 *
 * Full access is one state, not two. A token nobody has ever restricted and a
 * token an administrator has granted all of have the same access, and showing
 * them as "Unrestricted" and "22 of 22" next to each other made two identical
 * rows look different (and made a saved full matrix look like a narrowing).
 * Which of the two a token is, is provenance rather than access, so it belongs
 * in the tooltip and in the permissions popup, where the matrix itself is.
 */
type AccessState = "unrestricted" | "restricted" | "none";

const accessStateOf = (permissions: AdminToken["permissions"]): AccessState => {
  const { granted, total } = permissions;
  if (granted === total) return "unrestricted";
  if (granted === 0) return "none";
  return "restricted";
};

/** What the Access badge is claiming, spelled out, for its tooltip. */
const accessDetail = (permissions: AdminToken["permissions"]) => {
  const { configured, granted, total } = permissions;

  switch (accessStateOf(permissions)) {
    case "unrestricted":
      return configured
        ? `All ${total} permissions, granted explicitly. Open Permissions to narrow them.`
        : `All ${total} permissions. No administrator has restricted this token, so it can call every module.`;
    case "none":
      return `No permissions. All ${total} are switched off for this token.`;
    default:
      return `${granted} of ${total} permissions. The rest are switched off for this token.`;
  }
};

/** Case-insensitive substring over any of the given fields; a blank filter
    matches everything, so an untouched control never hides a row. */
const matchesText = (needle: string, ...fields: (string | null)[]) => {
  const term = needle.trim().toLowerCase();
  if (!term) return true;
  return fields.some((field) => (field || "").toLowerCase().includes(term));
};

const matchesFilters = (token: AdminToken, filters: Record<FilterKey, string>) => {
  // Exact environment match, including the "no environment" case. This is a
  // picker, so there is no typing to be lenient about.
  if (filters.env === NO_ENVIRONMENT) {
    if (token.env_id) return false;
  } else if (filters.env && token.env_id !== filters.env) {
    return false;
  }

  if (!matchesText(filters.tokenId, token.id)) return false;
  if (!matchesText(filters.client, token.client_name)) return false;
  if (!matchesText(filters.account, token.account_id)) return false;
  if (!matchesText(filters.creator, token.creator_email, token.creator_name)) return false;

  // Through the same helper the badge uses, so choosing "Unrestricted" can
  // never hide a row whose badge says Unrestricted, or show one whose badge
  // says something else.
  if (filters.access && accessStateOf(token.permissions) !== filters.access) return false;

  if (filters.validity) {
    const expiresAt = token.token_expires_at
      ? new Date(token.token_expires_at).getTime()
      : null;

    if (filters.validity === "unknown") {
      if (expiresAt !== null) return false;
    } else {
      if (expiresAt === null) return false;
      const days = (expiresAt - Date.now()) / MS_PER_DAY;
      if (filters.validity === "expired" && days >= 0) return false;
      if (filters.validity === "soon" && (days < 0 || days > EXPIRY_WARNING_DAYS)) return false;
      if (filters.validity === "valid" && days <= EXPIRY_WARNING_DAYS) return false;
    }
  }

  if (filters.updated) {
    // Falls back to creation time: a token that has never been used still has
    // an age, and "last updated" is the only recency signal this table has.
    const stamp = token.updated_at || token.created_at;
    if (filters.updated === "never") return !token.updated_at;
    if (!stamp) return false;
    const age = Date.now() - new Date(stamp).getTime();
    if (!(age <= RANGE_MS[filters.updated])) return false;
  }

  if (filters.status === "active" && !token.is_active) return false;
  if (filters.status === "inactive" && token.is_active) return false;

  return true;
};

export interface TokensTableProps {
  tokens: AdminToken[];
  loading: boolean;
  onPermissions: (token: AdminToken) => void;
  onToggleStatus: (token: AdminToken, next: boolean) => void | Promise<void>;
  /** Opens the Activity Log page scoped to this token. */
  onActivityLogs: (token: AdminToken) => void;
  /**
   * An environment the admin arrived here asking about, sent by the
   * Environments table's "View tokens" action. Applied to the environment
   * filter; a fresh object per click is what makes clicking the same
   * environment twice work after the filter was cleared in between.
   */
  envScope?: { id: string; name: string } | null;
  /** Tells the parent its scope is no longer applied. */
  onClearEnvScope?: () => void;
}

export function TokensTable({
  tokens,
  loading,
  onPermissions,
  onToggleStatus,
  onActivityLogs,
  envScope = null,
  onClearEnvScope,
}: TokensTableProps) {
  const columns = useMemo<ColumnDef<AdminToken>[]>(
    () => [
      {
        id: "token",
        header: "Token",
        // The client name rides along so the toolbar search finds a token by
        // what is using it, not only by its environment.
        accessor: (token) =>
          [token.environment_name, token.client_name].filter(Boolean).join(" "),
        // Environment name, what the token was issued to, and the token's own
        // id in one cell, the way the Environments table shows an environment:
        // the id is what identifies the row for support (and what its
        // permissions are keyed on), so it stays visible and copyable without
        // costing a 36-character column. The client name matters here now that
        // a person can hold several tokens in one environment: without it, two
        // rows named PROD look identical.
        cell: (token) => (
          <div className="tok-name-cell">
            <div className="tok-name-row">
              <strong>
                {token.environment_name || <span className="text-muted">{EMPTY}</span>}
              </strong>
              {token.client_name && (
                <span className="tok-client" title="Issued to">
                  {token.client_name}
                </span>
              )}
            </div>
            <div className="action-cell tok-id-row">
              <code className="tok-id-code">{token.id}</code>
              <CopyButton value={token.id} title="Copy token ID" />
            </div>
          </div>
        ),
      },
      {
        id: "account_id",
        header: "Account ID",
        accessor: (token) => token.account_id,
        cell: (token) =>
          token.account_id ? token.account_id : <span className="text-muted">{EMPTY}</span>,
      },
      {
        id: "creator",
        header: "Generated By",
        accessor: (token) => token.creator_email,
        cell: (token) =>
          token.creator_email ? (
            <div className="tok-creator">
              <span>{token.creator_email}</span>
              {token.creator_name && (
                <span className="tok-creator-name">{token.creator_name}</span>
              )}
            </div>
          ) : (
            <span className="text-muted">{EMPTY}</span>
          ),
      },
      {
        id: "access",
        header: "Access",
        // Sorts on the number granted, so the most restricted tokens group
        // together instead of the alphabetical order of their labels. A token
        // nobody has restricted is summarised as fully granted, so it sorts
        // with full access rather than at zero.
        accessor: (token) => token.permissions.granted,
        cell: (token) => {
          const { granted, total } = token.permissions;
          const state = accessStateOf(token.permissions);

          return (
            // Badge has no title prop, and the difference between a token that
            // was never restricted and one that was granted everything is a
            // fact about its history, not its access, so it lives here.
            //
            // One colour per state, on a scale an admin can read down the
            // column without reading the words: green for every permission,
            // amber for a narrowed set, red for none. Same ordering the
            // Validity column uses, so the two columns colour the same way.
            <span title={accessDetail(token.permissions)}>
              {state === "unrestricted" && (
                <Badge tone="success" icon="fa-solid fa-unlock">
                  Unrestricted
                </Badge>
              )}
              {state === "none" && (
                <Badge tone="danger" icon="fa-solid fa-ban">
                  No access
                </Badge>
              )}
              {state === "restricted" && (
                <Badge tone="warning" icon="fa-solid fa-key">
                  {granted} of {total}
                </Badge>
              )}
            </span>
          );
        },
      },
      {
        id: "validity",
        header: "Validity",
        // Sorts on the expiry itself, so whatever is closest to breaking sits
        // at the top of the list.
        accessor: (token) => dateSortValue(token.token_expires_at),
        cell: (token) => {
          const validity = validityOf(token);
          return (
            // Badge has no title prop, and the exact timestamp is what an
            // admin needs once the label tells them a token is worth a look.
            <span title={validity.detail}>
              <Badge tone={validity.tone}>{validity.label}</Badge>
            </span>
          );
        },
      },
      {
        id: "is_active",
        header: "Status",
        width: "92px",
        sortable: false,
        cell: (token) => (
          <Toggle
            size="sm"
            checked={token.is_active}
            title={token.is_active ? "Token is active" : "Token is switched off"}
            ariaLabel={`Status for token ${token.id}`}
            onToggle={(next) => onToggleStatus(token, next)}
          />
        ),
      },
      {
        id: "actions",
        header: "Actions",
        width: "64px",
        align: "center",
        className: "tok-actions-col",
        headerClassName: "tok-actions-col",
        cell: (token) => (
          <RowMenu
            label={`Actions for token ${token.id}`}
            items={[
              {
                label: "Permissions",
                icon: "fa-solid fa-shield-halved",
                onSelect: () => onPermissions(token),
              },
              {
                label: "Activity logs",
                icon: "fa-solid fa-clock-rotate-left",
                onSelect: () => onActivityLogs(token),
              },
              {
                label: "Copy token ID",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  navigator.clipboard?.writeText(token.id).catch(() => {});
                },
              },
              {
                // The username is the value a caller authenticates with and it
                // is no longer a column (it repeats the account id, the
                // environment and the email), so it stays reachable here.
                label: "Copy username",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  if (token.username) {
                    navigator.clipboard?.writeText(token.username).catch(() => {});
                  }
                },
              },
              {
                label: token.is_active ? "Deactivate" : "Activate",
                icon: "fa-solid fa-power-off",
                danger: token.is_active,
                onSelect: () => onToggleStatus(token, !token.is_active),
              },
            ]}
          />
        ),
      },
    ],
    [onPermissions, onToggleStatus, onActivityLogs],
  );

  const [filters, setFilters] = useState<Record<FilterKey, string>>(EMPTY_FILTERS);
  const [filtersOpen, setFiltersOpen] = useState(false);
  // Fixed-position coordinates for the portalled popup, measured from the
  // button when it opens (null until then).
  const [popupPosition, setPopupPosition] = useState<{ top: number; left: number } | null>(
    null,
  );
  const filterButtonRef = useRef<HTMLButtonElement>(null);
  const popupRef = useRef<HTMLDivElement>(null);

  // Below this width the popup stops being a floating panel and becomes a
  // bottom sheet. A 460px panel on a 360px viewport is unusable either way.
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const query = window.matchMedia("(max-width: 640px)");
    const sync = () => setIsMobile(query.matches);
    sync();
    query.addEventListener("change", sync);
    return () => query.removeEventListener("change", sync);
  }, []);

  const setFilter = (key: FilterKey, value: string) =>
    setFilters((prev) => ({ ...prev, [key]: value }));

  const clearFilters = () => setFilters(EMPTY_FILTERS);

  const activeFilterCount = Object.values(filters).filter(Boolean).length;

  // The Environments table's "View tokens" action lands here, so the
  // environment filter has to follow it. Only the environment filter is
  // touched: arriving from an environment row should not silently drop a
  // filter the admin had already set by hand.
  useEffect(() => {
    setFilters((prev) => ({ ...prev, env: envScope ? envScope.id : "" }));
  }, [envScope]);

  // Filtered here rather than inside useTable: which rows are "in" is this
  // page's business (it owns the filter definitions), and useTable's contract
  // stays "sort, search and paginate this array".
  const visibleTokens = useMemo(
    () => tokens.filter((token) => matchesFilters(token, filters)),
    [tokens, filters],
  );

  // Environment choices come from the tokens themselves rather than from the
  // environments list: an environment that holds no tokens here could only
  // ever produce an empty table, so offering it would be a filter that lies.
  const environmentOptions = useMemo(() => {
    const byId = new Map<string, string>();
    let hasUnassigned = false;

    for (const token of tokens) {
      if (!token.env_id) {
        hasUnassigned = true;
        continue;
      }
      if (!byId.has(token.env_id)) {
        byId.set(token.env_id, token.environment_name || token.env_id);
      }
    }

    const options = [
      { value: "", label: "All environments" },
      ...[...byId.entries()]
        .sort((a, b) => a[1].localeCompare(b[1]))
        .map(([value, label]) => ({ value, label })),
    ];

    if (hasUnassigned) options.push({ value: NO_ENVIRONMENT, label: "No environment" });

    return options;
  }, [tokens]);

  // The chip beside the Filters button names whatever environment filter is
  // applied, whether it came from the Environments table or from the popup, so
  // "why is this list short?" always has an answer on screen. Resolved through
  // the same option list the picker uses, so the two can never disagree; the
  // scope's own name is the fallback for an environment that holds no tokens
  // yet and therefore has no option.
  const scopeLabel = filters.env
    ? environmentOptions.find((option) => option.value === filters.env)?.label ||
      (envScope?.id === filters.env ? envScope.name : null) ||
      filters.env
    : null;

  // Esc closes the filter popup, like every other popup in the console.
  const closeFilters = useCallback(() => {
    setFiltersOpen(false);
    setPopupPosition(null);
  }, []);

  useEffect(() => {
    if (!filtersOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") closeFilters();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [filtersOpen, closeFilters]);

  // Clicking anywhere outside closes it. A pointerdown listener rather than a
  // full-screen scrim, because the popup is portalled onto <body> and a scrim
  // there would swallow the click before AdminSelect's own panel saw it.
  useEffect(() => {
    if (!filtersOpen) return;
    const onPointerDown = (event: PointerEvent) => {
      const target = event.target as Node;
      if (popupRef.current?.contains(target)) return;
      if (filterButtonRef.current?.contains(target)) return;
      closeFilters();
    };
    document.addEventListener("pointerdown", onPointerDown);
    return () => document.removeEventListener("pointerdown", onPointerDown);
  }, [filtersOpen, closeFilters]);

  /* Measure after paint but before the browser shows the frame, so the popup
     never appears at the wrong spot for one frame, the same approach as RowMenu,
     which portals its menu for the same reason. Right-aligned to the button so
     it opens under the control that owns it, and flipped above when it would
     run off the bottom of the window. */
  useLayoutEffect(() => {
    // Nothing to measure on mobile: the sheet is pinned to the bottom of the
    // viewport by its own styles.
    if (!filtersOpen || isMobile) return;
    const trigger = filterButtonRef.current;
    const popup = popupRef.current;
    if (!trigger || !popup) return;

    const anchor = trigger.getBoundingClientRect();
    const { width, height } = popup.getBoundingClientRect();
    const edge = 8;

    let left = anchor.right - width;
    left = Math.max(edge, Math.min(left, window.innerWidth - width - edge));

    let top = anchor.bottom + 6;
    if (top + height > window.innerHeight - edge) {
      top = Math.max(edge, anchor.top - height - 6);
    }

    setPopupPosition({ top, left });
  }, [filtersOpen, isMobile]);

  const table = useTable({
    data: visibleTokens,
    columns,
    getRowId: (token) => token.id,
    initialPageSize: 10,
  });

  // Rendered into the DataTable toolbar slot, which puts it immediately to the
  // right of the search box. The filters themselves open in a popup rather
  // than sitting permanently above the table: the default view of this page is
  // the table, not a form.
  const filterControl = (
    <div className="tok-filter-wrap">
      <button
        ref={filterButtonRef}
        type="button"
        className={`tok-filter-toggle${filtersOpen ? " is-open" : ""}`}
        aria-expanded={filtersOpen}
        aria-haspopup="dialog"
        onClick={() => (filtersOpen ? closeFilters() : setFiltersOpen(true))}
      >
        <i className="fa-solid fa-filter" aria-hidden="true" />
        Filters
        {activeFilterCount > 0 && (
          <span className="tok-filter-count">{activeFilterCount}</span>
        )}
      </button>

      {scopeLabel && (
        <span className="tok-scope-chip" title={`Showing tokens for ${scopeLabel} only`}>
          <i className="fa-solid fa-layer-group" aria-hidden="true" />
          <span className="tok-scope-chip-label">{scopeLabel}</span>
          <button
            type="button"
            className="tok-scope-chip-clear"
            onClick={() => {
              setFilter("env", "");
              onClearEnvScope?.();
            }}
            aria-label="Clear the environment filter"
            title="Clear the environment filter"
          >
            <i className="fa-solid fa-xmark" aria-hidden="true" />
          </button>
        </span>
      )}

      {/* Portalled onto <body>: this table sits inside a .card, which clips
          its own overflow for the rounded corners, so an absolutely-positioned
          panel would be cut off at the card's edge. RowMenu portals its menu
          for exactly this reason. */}
      {filtersOpen &&
        createPortal(
          <>
            {isMobile && (
              <div
                className="tok-filter-backdrop"
                aria-hidden="true"
                onClick={closeFilters}
              />
            )}

            <div
              ref={popupRef}
              className={`tok-filter-popup${isMobile ? " tok-filter-sheet" : ""}`}
              role="dialog"
              aria-modal={isMobile || undefined}
              aria-label="Filter tokens"
              style={
                isMobile
                  ? undefined
                  : popupPosition
                    ? { top: popupPosition.top, left: popupPosition.left }
                    : // Measured in a layout effect the moment it mounts;
                      // hidden until then so it never flashes in the corner.
                      { top: 0, left: 0, visibility: "hidden" }
              }
            >
              {/* Sheet affordance. Hidden above the mobile breakpoint. */}
              <div className="tok-filter-sheet-handle" aria-hidden="true" />
            <div className="tok-filter-popup-head">
              <span className="tok-filter-popup-title">
                <i className="fa-solid fa-filter" aria-hidden="true" />
                Filter tokens
              </span>
              <button
                type="button"
                className="tok-filter-popup-close"
                aria-label="Close filters"
                onClick={closeFilters}
              >
                <i className="fa-solid fa-xmark" aria-hidden="true" />
              </button>
            </div>

            <div className="tok-filter-popup-body">
              {FILTER_DEFS.map((def) => (
                <div className="tok-filter-field" key={def.key}>
                  <div className="tok-filter-labelrow">
                    <label className="tok-filter-label" htmlFor={`tok-filter-${def.key}`}>
                      {def.label}
                    </label>
                    {/* Per-field clear, so undoing one choice does not mean
                        undoing every other one to do it. */}
                    {filters[def.key] ? (
                      <button
                        type="button"
                        className="tok-filter-fieldclear"
                        onClick={() => setFilter(def.key, "")}
                        aria-label={`Clear the ${def.label.toLowerCase()} filter`}
                        title="Clear this filter"
                      >
                        <i className="fa-solid fa-xmark" aria-hidden="true" />
                      </button>
                    ) : null}
                  </div>
                  {def.kind === "text" ? (
                    <input
                      id={`tok-filter-${def.key}`}
                      className="form-control"
                      type="text"
                      value={filters[def.key]}
                      placeholder={def.placeholder}
                      autoComplete="off"
                      onChange={(e) => setFilter(def.key, e.target.value)}
                    />
                  ) : (
                    <AdminSelect
                      id={`tok-filter-${def.key}`}
                      ariaLabel={`Filter by ${def.label.toLowerCase()}`}
                      value={filters[def.key]}
                      onChange={(value) => setFilter(def.key, value)}
                      // The environment list is the long one, so it keeps the
                      // type-to-narrow search; a three-state list is shorter
                      // than the search box would be.
                      searchable={def.kind === "environment"}
                      options={
                        def.kind === "environment" ? environmentOptions : def.options || []
                      }
                    />
                  )}
                </div>
              ))}
            </div>

            <div className="tok-filter-popup-foot">
              <span className="tok-filter-popup-count" aria-live="polite">
                {visibleTokens.length} of {tokens.length} token
                {tokens.length === 1 ? "" : "s"}
              </span>
              <div className="tok-filter-popup-actions">
                <button
                  type="button"
                  className="btn btn-ghost"
                  onClick={clearFilters}
                  disabled={activeFilterCount === 0}
                >
                  Clear all
                </button>
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={closeFilters}
                >
                  Done
                </button>
              </div>
            </div>
          </div>,
          </>,
          document.body,
        )}
    </div>
  );

  return (
    <DataTable
      table={table}
      caption="API Tokens"
      loading={loading}
      className="tok-table"
      searchPlaceholder="Search by environment, account or user…"
      toolbar={filterControl}
        empty={
          activeFilterCount > 0 ? (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-filter" aria-hidden="true" />
              </div>
              <h3>No tokens match those filters</h3>
              <p>
                {tokens.length} token{tokens.length === 1 ? "" : "s"} loaded, and none of
                them match every filter above.
              </p>
              <button type="button" className="btn btn-primary" onClick={clearFilters}>
                <i className="fa-solid fa-xmark" aria-hidden="true" /> Clear filters
              </button>
            </div>
          ) : (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-key" aria-hidden="true" />
              </div>
              <h3>No API tokens yet</h3>
              <p>
                Tokens appear here as soon as a user generates one from the environment login
                page.
              </p>
            </div>
          )
        }
      />
  );
}
