import { useMemo, useState } from "react";
import type { AdminToken } from "../../lib/tokenPermissionsApi";
import { DataTable } from "../../components/ui/DataTable";
import { useTable, type ColumnDef } from "../../components/ui/useTable";
import { RowMenu } from "../../components/ui/RowMenu";
import { CopyButton } from "../../components/ui/CopyButton";
import { Toggle } from "../../components/ui/Toggle";
import { Badge } from "../../components/ui/Badge";
import AdminSelect from "../../components/AdminSelect";
import { EMPTY, dateSortValue, formatDateTime } from "../../lib/format";
import "./TokensTable.css";

/* The API Tokens table — one row per token record the token service has
 * issued, with the module permissions that govern it reachable from the row
 * itself (the modal is owned by AdminDashboard, exactly as the portal-user
 * permissions modal is).
 *
 * The row deliberately shows the token's *identity* — which environment and
 * account it acts for, which Wrike user generated it, and what it is allowed
 * to do — and never the credential it carries. An admin who needs the token
 * value uses the console's token tooling; this screen can't leak it because
 * the API never sends it. */

/* ── Advanced filters ─────────────────────────────────────────────────
   The table's own search box is one substring over the whole row; this is
   the per-column version of it, one control per column that can meaningfully
   be narrowed (every column except Actions, which is a menu).

   The definitions below are the single authority: they render the controls
   and they decide what each control matches, so a filter can never be
   displayed without being applied or applied without being displayed. */

type FilterKey = "token" | "account" | "creator" | "access" | "updated" | "status";

interface FilterDef {
  key: FilterKey;
  label: string;
  kind: "text" | "select";
  placeholder?: string;
  options?: { value: string; label: string }[];
}

const FILTER_DEFS: FilterDef[] = [
  {
    key: "token",
    label: "Token",
    kind: "text",
    placeholder: "Environment or token id",
  },
  { key: "account", label: "Account ID", kind: "text", placeholder: "Account id" },
  { key: "creator", label: "Generated by", kind: "text", placeholder: "Email or name" },
  {
    key: "access",
    label: "Access",
    kind: "select",
    // The three states the Access badge can be in, so the filter and the
    // column it filters speak the same language.
    options: [
      { value: "", label: "Any access" },
      { value: "unrestricted", label: "Unrestricted" },
      { value: "restricted", label: "Restricted" },
      { value: "none", label: "No access" },
    ],
  },
  {
    key: "updated",
    label: "Last updated",
    kind: "select",
    // A relative range rather than a date box: the column shows "3 days ago"
    // style recency, and typing an exact timestamp to find recent activity
    // would be worse than the three ranges people actually ask for.
    options: [
      { value: "", label: "Any time" },
      { value: "24h", label: "Last 24 hours" },
      { value: "7d", label: "Last 7 days" },
      { value: "30d", label: "Last 30 days" },
      { value: "never", label: "Never updated" },
    ],
  },
  {
    key: "status",
    label: "Status",
    kind: "select",
    options: [
      { value: "", label: "Any status" },
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
  },
];

const EMPTY_FILTERS: Record<FilterKey, string> = {
  token: "",
  account: "",
  creator: "",
  access: "",
  updated: "",
  status: "",
};

const RANGE_MS: Record<string, number> = {
  "24h": 24 * 60 * 60 * 1000,
  "7d": 7 * 24 * 60 * 60 * 1000,
  "30d": 30 * 24 * 60 * 60 * 1000,
};

/** Case-insensitive substring over any of the given fields; a blank filter
    matches everything, so an untouched control never hides a row. */
const matchesText = (needle: string, ...fields: (string | null)[]) => {
  const term = needle.trim().toLowerCase();
  if (!term) return true;
  return fields.some((field) => (field || "").toLowerCase().includes(term));
};

const matchesFilters = (token: AdminToken, filters: Record<FilterKey, string>) => {
  if (!matchesText(filters.token, token.environment_name, token.id)) return false;
  if (!matchesText(filters.account, token.account_id)) return false;
  if (!matchesText(filters.creator, token.creator_email, token.creator_name)) return false;

  const { configured, granted } = token.permissions;
  if (filters.access === "unrestricted" && configured) return false;
  if (filters.access === "restricted" && (!configured || granted === 0)) return false;
  if (filters.access === "none" && !(configured && granted === 0)) return false;

  if (filters.updated) {
    // Falls back to creation time: a token that has never been used still has
    // an age, and "last updated" is the only recency signal this table has.
    const stamp = token.updated_at || token.created_at;
    if (filters.updated === "never") return !token.updated_at;
    if (!stamp) return false;
    const age = Date.now() - new Date(stamp).getTime();
    if (!(age <= RANGE_MS[filters.updated])) return false;
  }

  if (filters.status === "active" && !token.is_active) return false;
  if (filters.status === "inactive" && token.is_active) return false;

  return true;
};

export interface TokensTableProps {
  tokens: AdminToken[];
  loading: boolean;
  onPermissions: (token: AdminToken) => void;
  onToggleStatus: (token: AdminToken, next: boolean) => void | Promise<void>;
  /** Opens the Activity Log page scoped to this token. */
  onActivityLogs: (token: AdminToken) => void;
}

export function TokensTable({
  tokens,
  loading,
  onPermissions,
  onToggleStatus,
  onActivityLogs,
}: TokensTableProps) {
  const columns = useMemo<ColumnDef<AdminToken>[]>(
    () => [
      {
        id: "token",
        header: "Token",
        accessor: (token) => token.environment_name,
        // Environment name and the token's own id in one cell, the way the
        // Environments table shows an environment: the id is what identifies
        // the row for support (and what its permissions are keyed on), so it
        // stays visible and copyable without costing a 36-character column.
        cell: (token) => (
          <div className="tok-name-cell">
            <strong>
              {token.environment_name || <span className="text-muted">{EMPTY}</span>}
            </strong>
            <div className="action-cell tok-id-row">
              <code className="tok-id-code">{token.id}</code>
              <CopyButton value={token.id} title="Copy token ID" />
            </div>
          </div>
        ),
      },
      {
        id: "account_id",
        header: "Account ID",
        accessor: (token) => token.account_id,
        cell: (token) =>
          token.account_id ? token.account_id : <span className="text-muted">{EMPTY}</span>,
      },
      {
        id: "creator",
        header: "Generated By",
        accessor: (token) => token.creator_email,
        cell: (token) =>
          token.creator_email ? (
            <div className="tok-creator">
              <span>{token.creator_email}</span>
              {token.creator_name && (
                <span className="tok-creator-name">{token.creator_name}</span>
              )}
            </div>
          ) : (
            <span className="text-muted">{EMPTY}</span>
          ),
      },
      {
        id: "access",
        header: "Access",
        // Sorts on the number granted, so the most restricted tokens group
        // together instead of the alphabetical order of their labels.
        accessor: (token) =>
          token.permissions.configured ? token.permissions.granted : token.permissions.total,
        cell: (token) => {
          const { configured, granted, total } = token.permissions;

          if (!configured) {
            return (
              <Badge tone="neutral" icon="fa-solid fa-unlock" >
                Unrestricted
              </Badge>
            );
          }

          if (granted === 0) {
            return (
              <Badge tone="danger" icon="fa-solid fa-ban">
                No access
              </Badge>
            );
          }

          return (
            <Badge tone="info" icon="fa-solid fa-key">
              {granted} of {total}
            </Badge>
          );
        },
      },
      {
        id: "updated_at",
        header: "Last Updated",
        accessor: (token) => dateSortValue(token.updated_at),
        cell: (token) => formatDateTime(token.updated_at),
        searchable: false,
      },
      {
        id: "is_active",
        header: "Status",
        width: "92px",
        sortable: false,
        cell: (token) => (
          <Toggle
            size="sm"
            checked={token.is_active}
            title={token.is_active ? "Token is active" : "Token is switched off"}
            ariaLabel={`Status for token ${token.id}`}
            onToggle={(next) => onToggleStatus(token, next)}
          />
        ),
      },
      {
        id: "actions",
        header: "Actions",
        width: "64px",
        align: "center",
        className: "tok-actions-col",
        headerClassName: "tok-actions-col",
        cell: (token) => (
          <RowMenu
            label={`Actions for token ${token.id}`}
            items={[
              {
                label: "Permissions",
                icon: "fa-solid fa-shield-halved",
                onSelect: () => onPermissions(token),
              },
              {
                label: "Activity logs",
                icon: "fa-solid fa-clock-rotate-left",
                onSelect: () => onActivityLogs(token),
              },
              {
                label: "Copy token ID",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  navigator.clipboard?.writeText(token.id).catch(() => {});
                },
              },
              {
                // The username is the value a caller authenticates with and it
                // is no longer a column (it repeats the account id, the
                // environment and the email), so it stays reachable here.
                label: "Copy username",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  if (token.username) {
                    navigator.clipboard?.writeText(token.username).catch(() => {});
                  }
                },
              },
              {
                label: token.is_active ? "Deactivate" : "Activate",
                icon: "fa-solid fa-power-off",
                danger: token.is_active,
                onSelect: () => onToggleStatus(token, !token.is_active),
              },
            ]}
          />
        ),
      },
    ],
    [onPermissions, onToggleStatus, onActivityLogs],
  );

  const [filters, setFilters] = useState<Record<FilterKey, string>>(EMPTY_FILTERS);
  const [filtersOpen, setFiltersOpen] = useState(false);

  const setFilter = (key: FilterKey, value: string) =>
    setFilters((prev) => ({ ...prev, [key]: value }));

  const clearFilters = () => setFilters(EMPTY_FILTERS);

  const activeFilterCount = Object.values(filters).filter(Boolean).length;

  // Filtered here rather than inside useTable: which rows are "in" is this
  // page's business (it owns the filter definitions), and useTable's contract
  // stays "sort, search and paginate this array".
  const visibleTokens = useMemo(
    () => tokens.filter((token) => matchesFilters(token, filters)),
    [tokens, filters],
  );

  const table = useTable({
    data: visibleTokens,
    columns,
    getRowId: (token) => token.id,
    initialPageSize: 10,
  });

  return (
    <>
      <div className="tok-filters">
        <button
          type="button"
          className={`tok-filter-toggle${filtersOpen ? " is-open" : ""}`}
          aria-expanded={filtersOpen}
          onClick={() => setFiltersOpen((open) => !open)}
        >
          <i className="fa-solid fa-filter" aria-hidden="true" />
          Filters
          {activeFilterCount > 0 && (
            <span className="tok-filter-count">{activeFilterCount}</span>
          )}
        </button>

        <span className="tok-filter-summary" aria-live="polite">
          {activeFilterCount > 0
            ? `Showing ${visibleTokens.length} of ${tokens.length} tokens`
            : `${tokens.length} token${tokens.length === 1 ? "" : "s"}`}
        </span>

        {activeFilterCount > 0 && (
          <button type="button" className="tok-filter-clear" onClick={clearFilters}>
            <i className="fa-solid fa-xmark" aria-hidden="true" />
            Clear all
          </button>
        )}
      </div>

      {filtersOpen && (
        <div className="tok-filter-panel">
          {FILTER_DEFS.map((def) => (
            <div className="tok-filter-field" key={def.key}>
              <label className="tok-filter-label" htmlFor={`tok-filter-${def.key}`}>
                {def.label}
              </label>
              {def.kind === "select" ? (
                <AdminSelect
                  id={`tok-filter-${def.key}`}
                  ariaLabel={`Filter by ${def.label.toLowerCase()}`}
                  value={filters[def.key]}
                  onChange={(value) => setFilter(def.key, value)}
                  searchable={false}
                  options={def.options || []}
                />
              ) : (
                <input
                  id={`tok-filter-${def.key}`}
                  className="form-control"
                  type="text"
                  value={filters[def.key]}
                  placeholder={def.placeholder}
                  autoComplete="off"
                  onChange={(e) => setFilter(def.key, e.target.value)}
                />
              )}
            </div>
          ))}
        </div>
      )}

      <DataTable
        table={table}
        caption="API Tokens"
        loading={loading}
        className="tok-table"
        searchPlaceholder="Search by environment, account or user…"
        empty={
          activeFilterCount > 0 ? (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-filter" aria-hidden="true" />
              </div>
              <h3>No tokens match those filters</h3>
              <p>
                {tokens.length} token{tokens.length === 1 ? "" : "s"} loaded — none of them
                match every filter above.
              </p>
              <button type="button" className="btn btn-primary" onClick={clearFilters}>
                <i className="fa-solid fa-xmark" aria-hidden="true" /> Clear filters
              </button>
            </div>
          ) : (
            <div className="dt2-empty">
              <div className="dt2-empty-icon">
                <i className="fa-solid fa-key" aria-hidden="true" />
              </div>
              <h3>No API tokens yet</h3>
              <p>
                Tokens appear here as soon as a user generates one from the environment login
                page.
              </p>
            </div>
          )
        }
      />
    </>
  );
}
