import { useMemo } from "react";
import type { AdminToken } from "../../lib/tokenPermissionsApi";
import { DataTable } from "../../components/ui/DataTable";
import { useTable, type ColumnDef } from "../../components/ui/useTable";
import { RowMenu } from "../../components/ui/RowMenu";
import { CopyButton } from "../../components/ui/CopyButton";
import { Toggle } from "../../components/ui/Toggle";
import { Badge } from "../../components/ui/Badge";
import { EMPTY, dateSortValue, formatDateTime } from "../../lib/format";
import "./TokensTable.css";

/* The API Tokens table — one row per token record the token service has
 * issued, with the module permissions that govern it reachable from the row
 * itself (the modal is owned by AdminDashboard, exactly as the portal-user
 * permissions modal is).
 *
 * The row deliberately shows the token's *identity* — which environment and
 * account it acts for, which Wrike user generated it, and what it is allowed
 * to do — and never the credential it carries. An admin who needs the token
 * value uses the console's token tooling; this screen can't leak it because
 * the API never sends it. */

export interface TokensTableProps {
  tokens: AdminToken[];
  loading: boolean;
  onPermissions: (token: AdminToken) => void;
  onToggleStatus: (token: AdminToken, next: boolean) => void | Promise<void>;
}

export function TokensTable({
  tokens,
  loading,
  onPermissions,
  onToggleStatus,
}: TokensTableProps) {
  const columns = useMemo<ColumnDef<AdminToken>[]>(
    () => [
      {
        id: "token",
        header: "Token",
        accessor: (token) => token.environment_name,
        // Environment name and the token's own id in one cell, the way the
        // Environments table shows an environment: the id is what identifies
        // the row for support (and what its permissions are keyed on), so it
        // stays visible and copyable without costing a 36-character column.
        cell: (token) => (
          <div className="tok-name-cell">
            <strong>
              {token.environment_name || <span className="text-muted">{EMPTY}</span>}
            </strong>
            <div className="action-cell tok-id-row">
              <code className="tok-id-code">{token.id}</code>
              <CopyButton value={token.id} title="Copy token ID" />
            </div>
          </div>
        ),
      },
      {
        id: "account_id",
        header: "Account ID",
        accessor: (token) => token.account_id,
        cell: (token) =>
          token.account_id ? token.account_id : <span className="text-muted">{EMPTY}</span>,
      },
      {
        id: "creator",
        header: "Generated By",
        accessor: (token) => token.creator_email,
        cell: (token) =>
          token.creator_email ? (
            <div className="tok-creator">
              <span>{token.creator_email}</span>
              {token.creator_name && (
                <span className="tok-creator-name">{token.creator_name}</span>
              )}
            </div>
          ) : (
            <span className="text-muted">{EMPTY}</span>
          ),
      },
      {
        id: "access",
        header: "Access",
        // Sorts on the number granted, so the most restricted tokens group
        // together instead of the alphabetical order of their labels.
        accessor: (token) =>
          token.permissions.configured ? token.permissions.granted : token.permissions.total,
        cell: (token) => {
          const { configured, granted, total } = token.permissions;

          if (!configured) {
            return (
              <Badge tone="neutral" icon="fa-solid fa-unlock" >
                Unrestricted
              </Badge>
            );
          }

          if (granted === 0) {
            return (
              <Badge tone="danger" icon="fa-solid fa-ban">
                No access
              </Badge>
            );
          }

          return (
            <Badge tone="info" icon="fa-solid fa-key">
              {granted} of {total}
            </Badge>
          );
        },
      },
      {
        id: "updated_at",
        header: "Last Updated",
        accessor: (token) => dateSortValue(token.updated_at),
        cell: (token) => formatDateTime(token.updated_at),
        searchable: false,
      },
      {
        id: "is_active",
        header: "Status",
        width: "92px",
        sortable: false,
        cell: (token) => (
          <Toggle
            size="sm"
            checked={token.is_active}
            title={token.is_active ? "Token is active" : "Token is switched off"}
            ariaLabel={`Status for token ${token.id}`}
            onToggle={(next) => onToggleStatus(token, next)}
          />
        ),
      },
      {
        id: "actions",
        header: "Actions",
        width: "64px",
        align: "center",
        className: "tok-actions-col",
        headerClassName: "tok-actions-col",
        cell: (token) => (
          <RowMenu
            label={`Actions for token ${token.id}`}
            items={[
              {
                label: "Permissions",
                icon: "fa-solid fa-shield-halved",
                onSelect: () => onPermissions(token),
              },
              {
                label: "Copy token ID",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  navigator.clipboard?.writeText(token.id).catch(() => {});
                },
              },
              {
                // The username is the value a caller authenticates with and it
                // is no longer a column (it repeats the account id, the
                // environment and the email), so it stays reachable here.
                label: "Copy username",
                icon: "fa-regular fa-copy",
                onSelect: () => {
                  if (token.username) {
                    navigator.clipboard?.writeText(token.username).catch(() => {});
                  }
                },
              },
              {
                label: token.is_active ? "Deactivate" : "Activate",
                icon: "fa-solid fa-power-off",
                danger: token.is_active,
                onSelect: () => onToggleStatus(token, !token.is_active),
              },
            ]}
          />
        ),
      },
    ],
    [onPermissions, onToggleStatus],
  );

  const table = useTable({
    data: tokens,
    columns,
    getRowId: (token) => token.id,
    initialPageSize: 10,
  });

  return (
    <DataTable
      table={table}
      caption="API Tokens"
      loading={loading}
      className="tok-table"
      searchPlaceholder="Search by environment, account or user…"
      empty={
        <div className="dt2-empty">
          <div className="dt2-empty-icon">
            <i className="fa-solid fa-key" aria-hidden="true" />
          </div>
          <h3>No API tokens yet</h3>
          <p>
            Tokens appear here as soon as a user generates one from the environment login
            page.
          </p>
        </div>
      }
    />
  );
}
